// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDspnSO5Ruj6nP3Z2_IKuImOw91I0AnlSY',
    appId: '1:294018970894:android:22c8c03e6399980abad35f',
    messagingSenderId: '294018970894',
    projectId: 'fir-bd62c',
    storageBucket: 'fir-bd62c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyVaygemaF702dJ45OhtzEoZUlNgsvFf8',
    appId: '1:294018970894:ios:a626c8d4ae009f7ebad35f',
    messagingSenderId: '294018970894',
    projectId: 'fir-bd62c',
    storageBucket: 'fir-bd62c.appspot.com',
    androidClientId: '294018970894-5qaao84q41l1ltn4topu08uq5rvc3ane.apps.googleusercontent.com',
    iosClientId: '294018970894-5coi93tm2o8k83dtdpofu9sua3h1avnk.apps.googleusercontent.com',
    iosBundleId: 'com.blogspot.flutterboss.firebase.firebasedemo',
  );
}
